-- SP_GET_RM_CONTACTS_BY_COUNTRY_NAME.sql
-- 2024-06-18-19-29UTC

USE PACETechRefresh_UAT
-- USE PACE4
GO

CREATE OR ALTER PROCEDURE [dbo].[SP_GET_RM_CONTACTS_BY_COUNTRY_NAME]
(	
	@COUNTRY_DESCRIPTION	NVARCHAR(180)
)
AS
BEGIN
	SELECT dbo.FN_GET_RM_CONTACTS_BY_COUNTRY_NAME(@COUNTRY_DESCRIPTION) AS 'RM_CONTACTS'
END


-- END OF THIS FILE
