-- CAU_KeyValuePairs.sql
-- 2024-06-24 13:36 UTC

USE PACETechRefresh_UAT
-- USE PACE4
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


IF OBJECT_ID('dbo.CAU_KeyValuePairs', 'U') IS NOT NULL
BEGIN
    DROP TABLE dbo.CAU_KeyValuePairs
END
GO

CREATE TABLE [dbo].[CAU_KeyValuePairs] (
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Key] [nvarchar](255),
	[Value] [nvarchar](255) NULL

	PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	
) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [NonClusteredIndex-Key] ON [dbo].[CAU_KeyValuePairs]
(
	[Key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


INSERT INTO dbo.CAU_KeyValuePairs ([Key], [Value]) VALUES ('RESULT_DETAILS_SECTIONS_HEIGHT_IN_ROWS', '60')

-- For key FINSCAN_SANCTIONS_TO_CONSIDER, multiple values must be separated by pipe (|) character, like 'Aaa|Bbb|Ccc'
INSERT INTO dbo.CAU_KeyValuePairs ([Key], [Value]) VALUES ('FINSCAN_SANCTIONS_TO_CONSIDER', 'Sanctions Lists')


-- END OF THIS FILE
